### Genre Based Movie Recommander

In [129]:
import pandas as pd

In [130]:
data  = pd.read_csv("./data/movie_metadata.csv")
data.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [131]:
data.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [132]:
data.shape

(5043, 28)

In [133]:
# create a df with only relevant columns
df = data[["movie_title","genres", "director_name","duration","language","country","title_year",    "imdb_score","movie_imdb_link"]].copy()
df.head()

,movie_title,genres,director_name,duration,language,country,title_year,imdb_score,movie_imdb_link
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,James Cameron,178.0,English,USA,2009.0,7.9,http://www.imdb.com/title/tt0499549/?ref_=fn_t...
1,Pirates of the Caribbean: At World's End,Action|Adventure|Fantasy,Gore Verbinski,169.0,English,USA,2007.0,7.1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...
2,Spectre,Action|Adventure|Thriller,Sam Mendes,148.0,English,UK,2015.0,6.8,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
3,The Dark Knight Rises,Action|Thriller,Christopher Nolan,164.0,English,USA,2012.0,8.5,http://www.imdb.com/title/tt1345836/?ref_=fn_t...
4,Star Wars: Episode VII - The Force Awakens ...,Documentary,Doug Walker,NaN,NaN,NaN,NaN,7.1,http://www.imdb.com/title/tt5289954/?ref_=fn_t...

In [134]:
df.notnull().sum()

movie_title        5043
genres             5043
director_name      4939
duration           5028
language           5029
country            5038
title_year         4935
imdb_score         5043
movie_imdb_link    5043
dtype: int64

In [135]:
df["movie_title"].duplicated().sum()

np.int64(126)

In [136]:
df["movie_title"][df["movie_title"].duplicated()==True].sort_index()

137                          The Legend of Tarzan
187     The Twilight Saga: Breaking Dawn - Part 2
204                           Godzilla Resurgence
303                                           Pan
389                                Fantastic Four
                           ...
4942                                   Cat People
4950                            A Dog's Breakfast
4951                     Night of the Living Dead
4971                   The Last House on the Left
5012                                     Sabotage
Name: movie_title, Length: 126, dtype: object

In [137]:
df.drop_duplicates(subset=["movie_title"], inplace=True)
df["movie_title"][df["movie_title"].duplicated()==True].sort_index()

Series([], Name: movie_title, dtype: object)

In [138]:
df.dtypes

movie_title         object
genres              object
director_name       object
duration           float64
language            object
country             object
title_year         float64
imdb_score         float64
movie_imdb_link     object
dtype: object

In [139]:
df["movie_title"].astype("str")
df["imdb_score"].astype("float")
df["title_year"].astype("int")

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
# fectch all the genres

genres_all_movies = [df.loc[i]["genres"].split('|') for i in df.index]

# find the list of genres of all movies in order
genres = sorted(list(set([genre for sublist in genres_all_movies for genre in sublist])))
genres

['Action',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Film-Noir',
 'Game-Show',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'News',
 'Reality-TV',
 'Romance',
 'Sci-Fi',
 'Short',
 'Sport',
 'Thriller',
 'War',
 'Western']

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

# Split genres into lists
df["genres"] = df["genres"].str.split("|")

# # Multi-hot encoding
mlb = MultiLabelBinarizer()
genre_features = mlb.fit_transform(df["genres"])
genre_df = pd.DataFrame(genre_features, columns=mlb.classes_, index=df.index)

In [ ]:
import joblib

# Save MultiLabelBinarizer
joblib.dump(mlb, "./pickles/mlb_genre_encoder.joblib")

['mlb_genre_encoder.joblib']

In [ ]:
genre_df

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,...,Mystery,News,Reality-TV,Romance,Sci-Fi,Short,Sport,Thriller,War,Western
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5039,0,0,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,0,1,0,0
5040,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
5041,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
5042,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
genre_df.to_csv("./data/genre_data.csv")
df.to_json("./data/movie_data.json")